pjsip/subscriptions: Fix some sys.path.append's
Some tests are using sys.path.append('lib/python/asterisk') instead of
sys.path.append('lib/python') which is causing errors like
"ImportError: cannot import name Asterisk" in some environments.  Those
have been fixed and the import/from's adjusted accordingly

Change-Id: I77df9177ed693dc9941966d9643bb6f4ca890d16